return {
    items_to_destroy = {
        "Imprint of the Enhanced Minion",
        "Tavon's Burnished Gemstone",
        "Tavon's Polished Gemstone",
        "Brightedge",
        "Mardu's Mercurial Visor",
        "Wavethrasher",
        "Mardu's Maniacal Mask",
        "Tideslasher",
        "Skull of the Spire Servant",
        "Summoned: Nightblade",
        "Summoned: Darkshine Staff",
        "Solus' Polished Gemstone",
        "Solus' Marquise-Cut Gemstone",
        "Summoned: Kotahl's Tonic of Healing",
        "Summoned: Kotahl's Tonic of Clarity",
        "Summoned: Kotahl's Tonic of Refreshment",
        "Ether-Fused Shard",
        "Pail of Slop",
    },

    items_to_keep = {
        "Solus' Burnished Gemstone",
        "Ether-Fused Tea",
        "Void Shard",
        "Bulwark of Many Portals",
        "Flamekin-Baked Rolls",
        "Diffused Green Tonic",
        "Worlu's Windcloak",
        "Worlu's Prying Eyes",
        "Regal Tonic of Greater Healing",
        "Crystallized Sulfur",
        "Exalted Tonic of Healing",
        "Murky Energy Tonic",
        "Majestic Tonic of Healing",
        "Airkin-Baked Croissant",
        "Wand of Temporal Mastery",
        "Modulating Rod",
        "Rod of Mystical Transvergence",
        "Wand of Restless Modulation",
        "Summoned: Shir Birenj",
        "Summoned: Nepeta Mint Tea",
        "Aircrisp Apple",
        "Summoned: Sahdi's Emblem of the Enhanced Minion",
    },
}
